numbers = [10 , 20 , 15 ,30 , 30 , 11]
print(numbers)
numbers.insert(4, 40)
print(numbers)
numbers.remove(20)
print(numbers)
numbers.pop()
print(numbers)
print (10 in numbers)
print(numbers.index(30))
print(numbers.index(15))
print(numbers.count(30))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
copy = numbers.copy()
print(copy)
numbers.clear()
print(numbers)